### PR TITLE
Feat/1208 fix song tooltips

### LINKED ISSUE #1208: API for Song/PopupContentWithVote?id=416174 returns 500 (song popups do not work)
### Website
VocaDB

### Describe the bug
When hovering over a songlink on VocaDB, the popup doesn't show the information properly (server error 500)

image

Album, Artist and Tag -popups work normally:

https://vocadb.net/Album/PopupContent?id=28162
https://vocadb.net/Artist/PopupContent?id=885
https://vocadb.net/Tag/PopupContent?id=7854

### To Reproduce
1. Go to https://vocadb.net/S/416174 (or any page that has song entry links)
2. Hover over any songlink under "alternative versions"
3. See error

### Expected behavior
A song popup window should show up

### Desktop (please complete the following information):
 - OS: win10
 - Browser: firefox

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [x] Tested on the **[beta site](https://beta.vocadb.net)**
- ~~[ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**~~
- ~~[] Checked in **private mode**~~
- ~~[ ] Cleared **browser cache** and **cookies**~~
- [x] Checked the **DevTools console**
- [x] Checked the **syslog** (mods+ only)

2022-08-31 00:00:36.1936 [.NET ThreadPool Worker] ERROR An unhandled exception has occurred while executing the request. - System.InvalidOperationException The model item passed into the ViewDataDictionary is of type 'VocaDb.Model.DataContracts.Songs.SongWithPVAndVoteForApiContract', but this ViewDataDictionary instance requires a model item of type 'VocaDb.Model.DataContracts.Songs.SongWithPVAndVoteContract'. Void EnsureCompatible(System.Object)    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #1208.

This PR replaces qtip tooltips with React components, by using [react-overlays](https://github.com/react-bootstrap/react-overlays).

### CODE REVIEW

File: VocaDbWeb/Scripts/Components/Shared/Partials/Shared/HelpLabel.tsx [hunk 1]
```diff
@@ -1,34 +1,38 @@
...
+import OverlayTrigger from '@/Bootstrap/OverlayTrigger';
+import { QTipToolTip } from '@/QTip/QTipToolTip';
 import React from 'react';
 
 interface HelpLabelProps {
 	label: string;
-	title: string;
+	dangerouslySetInnerHTML: {
+		__html: string;
+	};
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Shared/Partials/Shared/HelpLabel.tsx:9]: TODO: Remove `dangerouslySetInnerHTML`.

File: VocaDbWeb/webpack.mix.js [hunk 2]
```diff
@@ -48,8 +48,6 @@ mix
 	.js('Scripts/libs.js', 'wwwroot/bundles/shared')
 
 	// SHARED BUNDLES
-	// Legacy common scripts - should be phased out
-	.scripts(['Scripts/VocaDb.js'], 'wwwroot/bundles/VocaDB.js')
```
Comment (ycanardeau) [inline VocaDbWeb/webpack.mix.js:52]: Finally removed legacy common scripts.
