### PR TITLE
Convert user details to React

### LINKED ISSUE #1053: External links not in alphabetical order
The external links on entries were usually in alphabetical order if I remember correctly. Not sure what order it follows now.

EDIT: I noticed that the links are in alphabetical order while being in edit mode.

### LINKED ISSUE #1064: Artist verification link broken on the user page
image

From discord: https://discord.com/channels/309072240639737866/666326527197315091/940900407285276692

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #1064.
Fixes #1053.

### CODE REVIEW

File: VocaDbWeb/Controllers/Api/UserApiController.cs [hunk 1]
```diff
@@ -841,5 +841,14 @@ public class PostStatusLimitedModel
 		[Authorize]
 		[EnableCors(AuthenticationConstants.AuthenticatedCorsApiPolicy)]
 		public AlbumForUserForApiContract GetAlbumForUser(int albumId) => GetAlbumForUser(_permissionContext.LoggedUserId, albumId);
+
+#nullable enable
+		[HttpGet("~/api/profiles/{name}")]
+		[ApiExplorerSettings(IgnoreApi = true)]
+		public UserDetailsForApiContract GetDetails(string name/* TODO: , int? artistId = null, bool? childVoicebanks = null */)
```
Comment (ycanardeau) [inline VocaDbWeb/Controllers/Api/UserApiController.cs:848]: TODO: VocaDbWeb/Controllers/Api/UserApiController.cs
```cs
/* TODO: , int? artistId = null, bool? childVoicebanks = null */
```

File: VocaDbWeb/Scripts/Components/User/UserDetails.tsx [hunk 2]
```diff
@@ -0,0 +1,369 @@
...
+						autoOpen={userDetailsStore.sfsCheckDialog.dialogVisible}
+						close={(): void =>
+							runInAction(() => {
+								userDetailsStore.sfsCheckDialog.dialogVisible = false;
+							})
+						}
+					>
+						{userDetailsStore.sfsCheckDialog.html && (
+							// HACK
+							// TODO: Replace this with React
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/User/UserDetails.tsx:255]: TODO: VocaDbWeb/Scripts/Components/User/UserDetails.tsx
```tsx
// TODO: Replace this with React
```

File: VocaDbWeb/Scripts/Stores/User/UserDetailsStore.ts [hunk 3]
```diff
@@ -0,0 +1,222 @@
...
+			userId === loginManager.loggedUserId,
+			canEditAllComments,
+			false,
+			latestComments,
+			true,
+		);
+		this.songLists = new UserSongListsStore(values, userId, userRepo, tagRepo);
+		this.sfsCheckDialog = new SfsCheckStore(lastLoginAddress, this.adminRepo);
+
+		// TODO: Use useStoreWithUpdateResults.
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Stores/User/UserDetailsStore.ts:178]: TODO: VocaDbWeb/Scripts/Stores/User/UserDetailsStore.ts
```ts
// TODO: Use useStoreWithUpdateResults.
```
