### PR TITLE
Feat/917 fix statistics

### LINKED ISSUE #917: VocaDB statistics broken
**Website**
https://vocadb.net/stats

**Describe the bug**
When I go to the statistics page and, for example, check on user edits, the values and names don't change despite changing the filter.
Overall:
grafik
Last month:
grafik
Last day:
grafik

It could be that other statistics are also affected. I haven't tried it out yet.

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #917.

### CODE REVIEW

File: VocaDbWeb/Controllers/StatsController.cs [hunk 1]
```diff
@@ -228,22 +230,28 @@ private ActionResult SimplePieChart(string title, string seriesName, ICollection
...
-		private StatsQueries.LocalizedValue[] GetTopValues<T>(Func<IQueryable<T>, IQueryable<StatsQueries.LocalizedValue>> func)
+#nullable enable
+		private StatsQueries.LocalizedValue[] GetTopValues<T>(Func<IQueryable<T>, IQueryable<StatsQueries.LocalizedValue>> func, DateTime? cutoff)
 			where T : class, IDatabaseObject
 		{
-			var name = $"{ControllerContext.RouteData.Values["action"]}_{ControllerContext.RouteData.Values["cutoff"]}";
-			return _cache.GetOrInsert($"report_{name}", new CacheItemPolicy { SlidingExpiration = TimeSpan.FromDays(1), Priority = CacheItemPriority.Default }, () =>
-			{
-				var data = _userRepository.HandleQuery(ctx =>
+			var name = $"{ControllerContext.RouteData.Values["action"]}_{cutoff?.Date}";
```
Comment (ycanardeau) [inline VocaDbWeb/Controllers/StatsController.cs:237]: Clients are supposed to send UTC time, so we don't need to consider time zones.

File: VocaDbWeb/Controllers/StatsController.cs [hunk 2]
```diff
@@ -228,22 +230,28 @@ private ActionResult SimplePieChart(string title, string seriesName, ICollection
 			});
 		}
 
-		private StatsQueries.LocalizedValue[] GetTopValues<T>(Func<IQueryable<T>, IQueryable<StatsQueries.LocalizedValue>> func)
+#nullable enable
+		private StatsQueries.LocalizedValue[] GetTopValues<T>(Func<IQueryable<T>, IQueryable<StatsQueries.LocalizedValue>> func, DateTime? cutoff)
 			where T : class, IDatabaseObject
 		{
-			var name = $"{ControllerContext.RouteData.Values["action"]}_{ControllerContext.RouteData.Values["cutoff"]}";
```
Comment (ycanardeau) [inline VocaDbWeb/Controllers/StatsController.cs:234]: `ControllerContext.RouteData.Values["cutoff"]` becomes `null`. However, `cutoff` includes minutes and seconds, so caching wasn't working correctly at all.
