### PR TITLE
Convert song details to React

### LINKED ISSUE #630: GoogleBot can't find the lyrics
Compare `あれ、なんだかアタシの名前みたい（笑）` with `site:vocadb.net あれ、なんだかアタシの名前みたい（笑）` on Google Search.

### LINKED ISSUE #799: Extra newline/space before the name of supporting artists on song pages
**Website**
VocaDB

**Describe the bug**
On song pages, if a supporting artist has an entry, there is a newline between the left parentheses and their name (rendered as an un-aesthetic space).

**To Reproduce**
1.  View https://vocadb.net/S/68929

```html
<td class="artistList">
					



<a class="artistLink" data-entry-id="10136" href="/Ar/10136" data-hasqtip="59" oldtitle="しろ, Sing782Shi" title="">シロ</a>, (babi&nbsp;<small class="muted">(Voice manipulator)</small>), (
<a class="artistLink" data-entry-id="3286" href="/Ar/3286" data-hasqtip="60" oldtitle="ででP" title="">dede</a>&nbsp;<small class="muted">(Voice manipulator)</small>), (
<a class="artistLink" data-entry-id="10329" href="/Ar/10329" data-hasqtip="61" oldtitle="渦音P" title="">FMIC7743</a>&nbsp;<small class="muted">(Voice manipulator)</small>), [...]
```

**Expected behavior**
No newline/space, as with supporting artists who do not have entries.

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #630.
Fixes #799.

### CODE REVIEW

File: VocaDbWeb/Scripts/Components/Song/Partials/SongInListsDialog.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+				autoOpen={songInListsStore.dialogVisible}
+				width={400}
+				close={(): void =>
+					runInAction(() => {
+						songInListsStore.dialogVisible = false;
+					})
+				}
+			>
+				{songInListsStore.contentHtml && (
+					// TODO: Replace this with React
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/Partials/SongInListsDialog.tsx:28]: TODO: VocaDbWeb/Scripts/Components/Song/Partials/SongInListsDialog.tsx
```tsx
// TODO: Replace this with React
```

File: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx [hunk 2]
```diff
@@ -0,0 +1,395 @@
...
+							linkAs={Link}
+							linkProps={{
+								to: `/Search?${qs.stringify({ searchType: SearchType.Song })}`,
+							}}
+						>
+							{t('ViewRes:Shared.Songs')}
+						</Breadcrumb.Item>
+					</>
+				}
+				// TODO: Head
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/SongDetails.tsx:103]: TODO: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx
```tsx
// TODO: Head
````

File: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx [hunk 3]
```diff
@@ -0,0 +1,395 @@
...
+				toolbar={
+					<>
+						{(model.originalPVs.length > 0 || model.otherPVs.length > 0) && (
+							<div id="pvPlayer" className="song-pv-player">
+								{songDetailsStore.previewHtml ? (
+									// HACK
+									// TODO: Replace this with React
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/SongDetails.tsx:110]: TODO: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx
```tsx
// TODO: Replace this with React
```

File: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx [hunk 4]
```diff
@@ -0,0 +1,395 @@
...
+									icons={{ primary: 'ui-icon-wrench' }}
+								>
+									Maintenance actions{/* TODO: localize */}
+								</JQueryUIButton>
+							</>
+						)}{' '}
+						<EntryStatusMessage
+							status={EntryStatus[model.status as keyof typeof EntryStatus]}
+						/>
+						{/* TODO: _AjaxLoader */}
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/SongDetails.tsx:270]: TODO: VocaDbWeb/Scripts/Components/Song/SongDetails.tsx
```tsx
/* TODO: _AjaxLoader */
```

File: VocaDbWeb/Scripts/Components/Song/SongRelated.tsx [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+	}, [model]);
+
+	return (
+		<SongDetailsTabs
+			model={model}
+			songDetailsStore={songDetailsStore}
+			tab="related"
+		>
+			{contentHtml && (
+				// TODO: Replace this with React
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/SongRelated.tsx:36]: TODO: VocaDbWeb/Scripts/Components/Song/SongRelated.tsx
```tsx
// TODO: Replace this with React
```

File: VocaDbWeb/Controllers/SongController.cs [hunk 6]
```diff
@@ -176,13 +176,13 @@ public ActionResult Details(int id = InvalidId, int albumId = 0)
 				prop.OpenGraph.Image = model.ThumbUrlMaxSize;
 			}
 
-			prop.CanonicalUrl = VocaUriBuilder.CreateAbsolute(Url.Action("Details", new { id })).ToString();
+			//prop.CanonicalUrl = VocaUriBuilder.CreateAbsolute(Url.Action("Details", new { id })).ToString();
```
Comment (ycanardeau) [inline VocaDbWeb/Controllers/SongController.cs:179]: Removed `prop.CanonicalUrl`.

File: VocaDbWeb/Scripts/Components/Event/EventDetails.tsx [hunk 7]
```diff
@@ -635,10 +634,11 @@ const EventDetails = (): React.ReactElement => {
 			)
 			.catch((error) => {
 				if (error.response) {
-					if (error.response.status === 404) navigate('/Error/NotFound');
+					if (error.response.status === 404)
+						window.location.href = '/Error/NotFound';
 				}
 			});
-	}, [id, navigate]);
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Event/EventDetails.tsx:641]: Do not pass `navigate` here. `useNavigate` triggers `useEffect`. See also https://github.com/remix-run/react-router/discussions/8465.

File: VocaDbWeb/Scripts/Components/Shared/Partials/Artist/ArtistLink.tsx [hunk 8]
```diff
@@ -28,7 +28,8 @@ const ArtistLink = ({
 				<ArtistTypeLabel
 					artistType={ArtistType[artist.artistType as keyof typeof ArtistType]}
 				/>
-			)}{' '}
+			)}
+			{typeLabel && ' '}
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Shared/Partials/Artist/ArtistLink.tsx:32]: Fixes #799.

File: VocaDbWeb/Scripts/Components/Song/SongBasicInfo.tsx [hunk 9]
```diff
@@ -0,0 +1,880 @@
...
+									<JQueryUIButton
+										as={SafeAnchor}
+										disabled={!loginManager.canEditTags}
+										icons={{ primary: 'ui-icon-tag' }}
+										onClick={songDetailsStore.tagsEditStore.show}
+										href="#"
+									>
+										{t('ViewRes:EntryDetails.EditTags')}
+									</JQueryUIButton>
+									{model.canRemoveTagUsages /* TODO: Use LoginManager. */ && (
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/Song/SongBasicInfo.tsx:442]: TODO: VocaDbWeb/Scripts/Components/Song/SongBasicInfo.tsx
```tsx
/* TODO: Use LoginManager. */
```
