### PR TITLE
Fix advanced search filters

### LINKED ISSUE #793: Advanced search filters not working
From: https://vocadb.net/discussion/topics/372

Advanced search filters do not seem to work.

https://vocadb.net/Search?searchType=Song

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #793.

Reference(s):

 - [c# - How do I reproduce the [FromUri] behavior for complex parameters in .NET Core 2.1 - Stack Overflow](https://stackoverflow.com/questions/51423649/how-do-i-reproduce-the-fromuri-behavior-for-complex-parameters-in-net-core-2/51426635#51426635)

### CODE REVIEW

File: VocaDbWeb/Models/Shared/AdvancedSearchFilterParams.cs [hunk 1]
```diff
@@ -0,0 +1,31 @@
+using Microsoft.AspNetCore.Mvc;
+using VocaDb.Model.Service.Search;
+
+namespace VocaDb.Web.Models.Shared
+{
+	public sealed record AdvancedSearchFilterParams
```
Comment (riipah) [inline VocaDbWeb/Models/Shared/AdvancedSearchFilterParams.cs:6]: Please add the stackoverflow link here too, so we will remember why it's here
