### PR TITLE
Replace ResponseCacheLocation.Any with ResponseCacheLocation.Client

### LINKED ISSUE #768: Tag tooltips are wrong
For every tag tooltip I'm getting "music producer".

### PR DESCRIPTION
**Pull request by ycanardeau**
Closes #768.

### CODE REVIEW

File: VocaDbWeb/Controllers/TagController.cs [hunk 1]
```diff
@@ -237,7 +237,6 @@ public ActionResult Merge(int id, int? targetTagId)
 			return RedirectToAction("Edit", new { id = targetTagId.Value });
 		}
 
-		[ResponseCache(Location = ResponseCacheLocation.Any, Duration = 3600)]
```
Comment (ycanardeau) [inline VocaDbWeb/Controllers/TagController.cs:240]: Can we simply disable ResponseCache, or should we change it to `[ResponseCache(Location = ResponseCacheLocation.Any, Duration = 3600, VaryByQueryKeys = new[] { "id", "lang" })]`?
