### PR TITLE
VocaDB Player

### LINKED ISSUE #1113: Issues with "VocaDB player" on beta website
I was testing the VocaDB player at the bottom on the beta website. I've been encountering some errors. It's not 100% reliable, but I'll try to provide information.

Browser: Microsoft Edge (Chromium) 100.0.1185.36
OS: Windows 10

1. Open song page such as [Next Nest](https://beta.vocadb.net/S/59428).
2. Click video, to start playing it.
3. Video starts playing, but sometimes without audio/video.
4. Sometimes this happens only after navigating to another song and attempting to play that. I can reproduce this almost 100% certainly after clicking a few songs/videos.

Errors that I saw in console:
* POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_FAILED from base.js:6290 
* Access to XMLHttpRequest at 'https://play.google.com/log?format=json&hasfast=true&authuser=0' from origin 'https://www.youtube-nocookie.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://play.google.com' that is not equal to the supplied origin.
* Failed to load resource: the server responded with a status of 500 () from /Song/PopupContentWithVote?id=160452:1 (sorry, I didn't get the content for this)
* Multiple 404s for resources, such as VocaDb.Model.Resources.json

### LINKED ISSUE #1114: Suggestions for VocaDB player
The VocaDB player (at the bottom) is a great feature. I have a few suggestions to improve it. Perhaps you have already considered them.

In general, I would copy YouTube as much as possible, because they have pretty good usability in this sense.

- [x] 1. When clicking video preview to begin playback, I think it should still play on the page, it was before. (be48d5fff77a14f9809eed5bc48e4364b6ad7c0f)
- [x] 2. When navigating away to another page, the video could continue playing as small thumbnail in lower corner. (be48d5fff77a14f9809eed5bc48e4364b6ad7c0f)
- [x] 3. Instead of right-clicking video preview, there could be popup icons for "add to queue" and "play now", similar to YouTube. Or perhaps hamburger menu. (6d9d3533023b2c85febd51171e4571e4cd194842)
- [x] 4. There could be an option to show play queue and save it as song list. (4e2a2300208483de0164112a836ac4121a77abc1)

Feel free to split this issue into multiple smaller ones and ask for clarifications if you're unsure what I meant.

### PR DESCRIPTION
**Pull request by ycanardeau**
Depends on #1100.

Fixes #1113.
Closes #1114.

References:
- [vocadb/VocaDbWeb/Scripts/ViewModels/PVs/](https://github.com/VocaDB/vocadb/tree/5304e764cf423f07b424e94266e415db40d11f28/VocaDbWeb/Scripts/ViewModels/PVs)
- [React Player](https://github.com/cookpete/react-player)
- [ニコニコ動画のHTML5外部プレイヤーをJavaScriptで操作する](https://blog.hayu.io/web/create/nicovideo-embed-player-api/)

### CODE REVIEW

File: VocaDbWeb/Scripts/Components/VdbPlayer/EmbedNiconico.tsx [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+
+	// Code from: https://blog.hayu.io/web/create/nicovideo-embed-player-api/.
+	private postMessage = (message: any): void => {
+		this.assertPlayerAttached();
+		if (!this.player) return;
+
+		this.player.contentWindow?.postMessage(
+			{
+				...message,
+				playerId: '1' /* Needs to be a string, not a number. */,
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/VdbPlayer/EmbedNiconico.tsx:232]: Needs to be a string, not a number.

File: VocaDbWeb/Scripts/Components/VdbPlayer/EmbedNiconico.tsx [hunk 2]
```diff
@@ -0,0 +1,311 @@
...
+					width="100%"
+					height="100%"
+					allowFullScreen
+					style={{ border: 'none' }}
+					// The player has to have the allow="autoplay" attribute.
+					// Otherwise it throws a NotAllowedError: "play() failed because the user didn't interact with the document first".
+					// See also: https://github.com/vimeo/player.js/issues/389.
+					// NOTE: An iframe element created by `PVPlayerNiconico.playerFactory.create` doesn't have the allow="autoplay" attribute,
+					// which causes the above issue when trying to autoplay a video.
+					allow="autoplay; fullscreen"
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/VdbPlayer/EmbedNiconico.tsx:304]: The player has to have the `allow="autoplay"` attribute. Otherwise it throws a `NotAllowedError: "play() failed because the user didn't interact with the document first"`. See also: https://github.com/vimeo/player.js/issues/389.
NOTE: An iframe element created by `PVPlayerNiconico.playerFactory.create` doesn't have the `allow="autoplay" attribute`, which causes the above issue when trying to autoplay a video.

File: VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx [hunk 3]
```diff
@@ -0,0 +1,459 @@
...
+								height: 9 * 25,
+								zIndex: 3939,
+						  }
+						: {
+								position: 'absolute',
+								left: vdbPlayer.playerBounds.x,
+								top: vdbPlayer.playerBounds.y,
+								width: vdbPlayer.playerBounds.width,
+								height: vdbPlayer.playerBounds.height,
+						  }),
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx:390]: The "nostalgic diva" player should only be used in one place at any time. I really want to use [react-reverse-portal](https://github.com/httptoolkit/react-reverse-portal) to build a player once, and move it anywhere, but it didn't work well with [@vocadb/nostalgic-diva](https://github.com/VocaDB/nostalgic-diva) for some reason.

File: VocaDbWeb/Scripts/Pages/Album/AlbumBasicInfo.tsx [hunk 4]
```diff
@@ -543,12 +542,6 @@ const AlbumBasicInfo = observer(
 						<p>{t('ViewRes.Album:Details.NoTracklist')}</p>
 					)}
 
-				{model.primaryPV && (
-					<div className="song-pv-player">
-						<EmbedPV pv={model.primaryPV} />
-					</div>
-				)}
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Pages/Album/AlbumBasicInfo.tsx:550]: Previews must be placed at the top of the page, so that they have a static position. The same goes for events. See also https://github.com/VocaDB/vocadb/issues/1114#issuecomment-1094994750.

File: VocaDbWeb/Scripts/Pages/Playlist/PlaylistIndex.tsx [hunk 5]
```diff
@@ -0,0 +1,288 @@
...
+
+			playQueue.addToQueue(
+				...items.map((item) => new PlayQueueItem(item.entry, item.pv)),
+			);
+
+			playQueue.unselectAll();
+		}, [playQueue]);
+
+		const handleClickAddToNewSongList = React.useCallback(() => {
+			// TODO: Implement.
```
Comment (ycanardeau) [inline VocaDbWeb/Scripts/Pages/Playlist/PlaylistIndex.tsx:60]: TODO: Implement.
